### ISSUE TITLE
CPPRestSDK dependency does not build with GCC 9.3

### ISSUE THREAD

**Issue by jackgerrits** [VowpalWabbit/reinforcement_learning#164]
The specified cpprestsdk dependency version does not build with GCC 9.3
```
# Checkout 2.10.1 version of cpprestsdk
git checkout e8dda215426172cd348e4d6d455141f40768bf47
```

```
g++ (Ubuntu 9.3.0-10ubuntu2) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

Build issue:
```
[  0%] Building CXX object src/CMakeFiles/cpprest.dir/http/client/http_client.cpp.o
In file included from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:105,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/json.h: In member function ‘web::json::value& web::json::array::operator[](web::json::array::size_type)’:
/home/jack/cpprestsdk/Release/include/cpprest/json.h:974:29: error: implicitly-declared ‘constexpr msl::safeint3::SafeInt<long unsigned int>::SafeInt(const msl::safeint3::SafeInt<long unsigned int>&)’ is deprecated [-Werror=deprecated-copy]
  974 |             if (nlastSize < nMinSize)
      |                             ^~~~~~~~
In file included from /home/jack/cpprestsdk/Release/include/cpprest/details/basic_types.h:29,
                 from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:92,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:5639:22: note: because ‘msl::safeint3::SafeInt<long unsigned int>’ has user-provided ‘msl::safeint3::SafeInt<T, E>& msl::safeint3::SafeInt<T, E>::operator=(const msl::safeint3::SafeInt<T, E>&) [with T = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 5639 |     SafeInt< T, E >& operator =( const SafeInt< T, E >& rhs ) SAFEINT_NOTHROW
      |                      ^~~~~~~~
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:6443:34: note:   initializing argument 1 of ‘bool msl::safeint3::operator<(msl::safeint3::SafeInt<U, E>, msl::safeint3::SafeInt<T, E>) [with T = long unsigned int; U = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 6443 | bool operator <( SafeInt< U, E > lhs, SafeInt< T, E > rhs ) SAFEINT_NOTHROW
      |                  ~~~~~~~~~~~~~~~~^~~
In file included from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:105,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/json.h:974:29: error: implicitly-declared ‘constexpr msl::safeint3::SafeInt<long unsigned int>::SafeInt(const msl::safeint3::SafeInt<long unsigned int>&)’ is deprecated [-Werror=deprecated-copy]
  974 |             if (nlastSize < nMinSize)
      |                             ^~~~~~~~
In file included from /home/jack/cpprestsdk/Release/include/cpprest/details/basic_types.h:29,
                 from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:92,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:5639:22: note: because ‘msl::safeint3::SafeInt<long unsigned int>’ has user-provided ‘msl::safeint3::SafeInt<T, E>& msl::safeint3::SafeInt<T, E>::operator=(const msl::safeint3::SafeInt<T, E>&) [with T = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 5639 |     SafeInt< T, E >& operator =( const SafeInt< T, E >& rhs ) SAFEINT_NOTHROW
      |                      ^~~~~~~~
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:6443:55: note:   initializing argument 2 of ‘bool msl::safeint3::operator<(msl::safeint3::SafeInt<U, E>, msl::safeint3::SafeInt<T, E>) [with T = long unsigned int; U = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 6443 | bool operator <( SafeInt< U, E > lhs, SafeInt< T, E > rhs ) SAFEINT_NOTHROW
      |                                       ~~~~~~~~~~~~~~~~^~~
In file included from /home/jack/cpprestsdk/Release/include/cpprest/http_msg.h:28,
                 from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:116,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/containerstream.h: In instantiation of ‘size_t Concurrency::streams::details::basic_container_buffer<_CollectionType>::in_avail() const [with _CollectionType = std::vector<unsigned char>; size_t = long unsigned int]’:
/home/jack/cpprestsdk/Release/include/cpprest/containerstream.h:116:24:   required from here
/home/jack/cpprestsdk/Release/include/cpprest/containerstream.h:124:38: error: implicitly-declared ‘constexpr msl::safeint3::SafeInt<long unsigned int>::SafeInt(const msl::safeint3::SafeInt<long unsigned int>&)’ is deprecated [-Werror=deprecated-copy]
  124 |             return (size_t)(writeend - readhead);
      |                            ~~~~~~~~~~^~~~~~~~~~~
In file included from /home/jack/cpprestsdk/Release/include/cpprest/details/basic_types.h:29,
                 from /home/jack/cpprestsdk/Release/src/pch/stdafx.h:92,
                 from /home/jack/cpprestsdk/Release/src/http/client/http_client.cpp:16:
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:5639:22: note: because ‘msl::safeint3::SafeInt<long unsigned int>’ has user-provided ‘msl::safeint3::SafeInt<T, E>& msl::safeint3::SafeInt<T, E>::operator=(const msl::safeint3::SafeInt<T, E>&) [with T = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 5639 |     SafeInt< T, E >& operator =( const SafeInt< T, E >& rhs ) SAFEINT_NOTHROW
      |                      ^~~~~~~~
/home/jack/cpprestsdk/Release/include/cpprest/details/SafeInt3.hpp:6053:48: note:   initializing argument 1 of ‘msl::safeint3::SafeInt<T, E> msl::safeint3::SafeInt<T, E>::operator-(msl::safeint3::SafeInt<T, E>) const [with T = long unsigned int; E = msl::safeint3::SafeIntInternal::SafeIntExceptionHandler<msl::safeint3::SafeIntException>]’
 6053 |     SafeInt< T, E > operator -(SafeInt< T, E > rhs) const SAFEINT_CPP_THROW
      |                                ~~~~~~~~~~~~~~~~^~~
```
